source "https://rubygems.org"

gem "lita"
gem "lita-slack"
gem "faye-websocket", "0.10.2"
gem "puma", "2.16.0"
gem "docker-api"

# Uncomment to use the HipChat adapter
# gem "lita-hipchat"

# Uncomment to use the IRC adapter
# gem "lita-irc"

# Add handlers to give Lita new functionality.
# For example:
# gem "lita-google-images"
# gem "lita-karma"
